baseURL = "/"
languageCode = "en-us"
title = " IntentAware"
theme = "kube"
#theme="gohugoioTheme"
description = "Kube is a professional  and a responsive Hugo theme for developers and designers that offers a documentation section mixed with a landing page and a blog"
Paginate = 4
[Params]
  RSSLink = "/index.xml"
  author = "IntentAware" # add your company name
  github = "" # add your github profile name
  twitter = "@intentaware" # add your twitter profile
  email = "vin@intentaware.com"


[[menu.main]]
    name = "Solutions"
    weight = -200
    url = "/solutions/"

[[menu.main]]
    name = "Case Studies"
    weight = -150
    url = "/docs/"
[[menu.main]]
    name = "Contact"
    weight = -50
    url = "/contact/"
