backend:
  name: github
  repo: vinpatel/intentaware # Path to your Github repository
  branch: master # Branch to update

publish_mode: editorial_workflow

media_folder: "images/uploads" # Media files will be stored in the repo under images/uploads

collections: # A list of collections the CMS should be able to edit
  - name: "casestudies" # Used in routes, e.g., /admin/collections/:slug/edit
    label: "Case Studies" # Used in the UI, e.g., "New Post"
    folder: "_casestudies" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Foo", name: "foo", widget: "foo"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
